Pivot table
OHDSI/Ares pull request #120
Opened 2022-04-22 10:05 UTC by Mikhail-iontsev

Closes https://github.com/OHDSI/Ares/issues/115

Added pivot table to the data quality results component.

2022-04-22 12:26 UTC, fdefalco commented on src/interface/views/release/DataQualityResults.vue
> +      pivotTableHeaders: [],
Is pivotTableHeaders used anywhere?

2022-04-22 12:54 UTC, fdefalco requested changes
Is there a way to filter the data fields available in the list to drag/drop? The columns CHECK_DESCRIPTION, CONCEPT_ID, EXECUTION_TIME, NUM_DENOMINATOR_ROWS, NUM_VIOLATED_ROWS, PCT_VIOLATED_ROWS, QUERY_TEXT,  THRESHOLD_VALUE, UNIT_CONCEPT_ID, WARNING, _row, and checkId should be removed.

If you click on the word 'Table' in the top left cell you can change the viewer type, can this be disabled?

Font family varies across the component (verdana) and Ares (Roboto).  Can we standardize on Roboto.  I prefer no bold text in the pivot view results column.

2022-04-22 14:25 UTC, Mikhail-iontsev commented
> Is there a way to filter the data fields available in the list to drag/drop? The columns CHECK_DESCRIPTION, CONCEPT_ID, EXECUTION_TIME, NUM_DENOMINATOR_ROWS, NUM_VIOLATED_ROWS, PCT_VIOLATED_ROWS, QUERY_TEXT, THRESHOLD_VALUE, UNIT_CONCEPT_ID, WARNING, _row, and checkId should be removed.
> 
> If you click on the word 'Table' in the top left cell you can change the viewer type, can this be disabled?
> 
> Font family varies across the component (verdana) and Ares (Roboto). Can we standardize on Roboto. I prefer no bold text in the pivot view results column.

1. Yes, we can. 
2.  We can disable the type change button but along with all the other interface elements except for the table itself. In this case we will need write separate row and column table constructors.
3. So the table headers can stay bold?

2022-04-22 14:43 UTC, fdefalco commented
3. I don't think they need to be bold. They can be consistent with the overview tab where the background color of the header row is differentiated but the font is not bold.

2022-04-22 21:18 UTC, Mikhail-iontsev commented
> 3. I don't think they need to be bold. They can be consistent with the overview tab where the background color of the header row is differentiated but the font is not bold.

So, there are two ways to disable the renderer type button: 

1. Just plain disable it, but the cell containing it remains: 
![Screenshot from 2022-04-23 00-11-33](https://user-images.githubusercontent.com/92372420/164794491-b1d9c148-b7ea-48e5-a7ee-521bc2ee9c4b.png)
2. Create custom controls: 
![Screenshot from 2022-04-23 00-15-17](https://user-images.githubusercontent.com/92372420/164795130-9ce1e444-050b-49d4-92b4-3a96f7ce0ec8.png)

Which one do you prefer?

2022-04-23 02:10 UTC, fdefalco commented
The custom controls seem to have a much more integrated appearance.  I prefer them.

2022-04-23 05:05 UTC, Mikhail-iontsev commented on src/interface/views/release/DataQualityResults.vue
> +      pivotTableHeaders: [],
Forgot to delete. It was created along with a few functions for a table using v-data-table component.

2022-04-25 12:18 UTC, fdefalco commented
Looks great.  Only issue is that the custom control font size is 16px, can you change to 14px?

2022-04-25 20:02 UTC, merged