Add back to table button for drilldown reports
OHDSI/Ares pull request #54
Opened 2021-12-01 01:05 UTC by Mikhail-iontsev

Closes https://github.com/OHDSI/Ares/issues/40

Added back button to drilldown reports, it's right to the report's name.

2021-12-01 10:56 UTC, arcadiaEvgenyLokets requested changes

2021-12-01 10:56 UTC, arcadiaEvgenyLokets commented on src/components/ReturnButton.vue
> +  <div class="back-button" @click="$router.go(-1)">
You can use just back method
```suggestion
  <div class="back-button" @click="$router.back">
```

2021-12-01 10:56 UTC, arcadiaEvgenyLokets commented on src/components/ReturnButton.vue
> +  <div class="back-button" @click="$router.go(-1)">
And try to do semantic markup. Eg Button tags for buttons.
Since we use vuetify you can use button component from vuetify library

2021-12-02 18:48 UTC, Mikhail-iontsev commented
Also added return button to exit from the error screen

2021-12-02 22:14 UTC, fdefalco commented
i'm seeing the back button on the network over view, shouldn't be on that page.

![image](https://user-images.githubusercontent.com/6586384/144511777-0fae4ba1-cb1a-4f05-a359-352127866e6e.png)

2021-12-02 22:25 UTC, Mikhail-iontsev commented
Removed the button from overview screen. It should now be present only in drill down reports and error pages

2021-12-03 10:06 UTC, arcadiaEvgenyLokets commented on src/components/DeathReport.vue
> +      <ReturnButton block />
You can set `block` to `true` as default value for prop instead of passing everywhere

2021-12-03 10:07 UTC, arcadiaEvgenyLokets commented on src/components/ReturnButton.vue
> +    block: Boolean
```suggestion
  name: "ReturnButton",
  props: {
    block: {
     type: Boolean,
     default: true
    }
```

2021-12-03 10:28 UTC, Mikhail-iontsev commented on src/components/DeathReport.vue
> +      <ReturnButton block />
The block prop is only used when the error is displayed. I'd like to move the error component to a wrapper in the future so that it's only used once, which means in this case the default value would be used less than false. Moreover, explicit true seems easier to understand than explicit false.

2021-12-03 10:32 UTC, arcadiaEvgenyLokets approved these changes

2021-12-03 16:11 UTC, fdefalco approved these changes

2021-12-03 16:12 UTC, merged